// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import Header from "@/components/header";
import { Footer } from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// app/layout.tsx
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full flex flex-col">
        <Providers>
          {/* Header fijo */}
          <Header />

          {/* Contenedor scrollable entre header y footer */}
          <div className="flex-1 overflow-hidden flex flex-col">
            {children}
          </div>

          {/* Footer fijo */}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}